//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escc.Search.Google.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SampleResponses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SampleResponses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escc.Search.Google.Tests.SampleResponses", typeof(SampleResponses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;kind&quot;: &quot;customsearch#search&quot;,
        /// &quot;url&quot;: {
        ///  &quot;type&quot;: &quot;application/json&quot;,
        ///  &quot;template&quot;: &quot;https://www.googleapis.com/customsearch/v1?q={searchTerms}&amp;num={count?}&amp;start={startIndex?}&amp;lr={language?}&amp;safe={safe?}&amp;cx={cx?}&amp;sort={sort?}&amp;filter={filter?}&amp;gl={gl?}&amp;cr={cr?}&amp;googlehost={googleHost?}&amp;c2coff={disableCnTwTranslation?}&amp;hq={hq?}&amp;hl={hl?}&amp;siteSearch={siteSearch?}&amp;siteSearchFilter={siteSearchFilter?}&amp;exactTerms={exactTerms?}&amp;excludeTerms={excludeTerms?}&amp;linkSite={linkSite?}&amp;orTerms={orTerms?}&amp;relatedSite={r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseAllFields {
            get {
                return ResourceManager.GetString("ExampleResponseAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;queries&quot;: {
        ///  &quot;nextPage&quot;: [
        ///   {
        ///    &quot;title&quot;: &quot;Google Custom Search - videos&quot;,
        ///    &quot;totalResults&quot;: &quot;194&quot;,
        ///    &quot;searchTerms&quot;: &quot;videos&quot;,
        ///    &quot;count&quot;: 10,
        ///    &quot;startIndex&quot;: 11,
        ///    &quot;inputEncoding&quot;: &quot;utf8&quot;,
        ///    &quot;outputEncoding&quot;: &quot;utf8&quot;,
        ///    &quot;safe&quot;: &quot;off&quot;,
        ///    &quot;cx&quot;: &quot;013802616358587036066:ehvcftnmyfs&quot;
        ///   }
        ///  ]
        /// },
        /// &quot;searchInformation&quot;: {
        ///  &quot;searchTime&quot;: 0.41761,
        ///  &quot;formattedSearchTime&quot;: &quot;0.42&quot;,
        ///  &quot;totalResults&quot;: &quot;194&quot;,
        ///  &quot;formattedTotalResults&quot;: &quot;194&quot;
        /// },
        /// &quot;items&quot;: [
        ///  {
        ///   &quot;title&quot;: &quot;Videos of council meetin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleResponseSelectedFields {
            get {
                return ResourceManager.GetString("ExampleResponseSelectedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        /// &quot;searchInformation&quot;: {
        ///  &quot;searchTime&quot;: 0.510932,
        ///  &quot;formattedSearchTime&quot;: &quot;0.51&quot;,
        ///  &quot;totalResults&quot;: &quot;0&quot;,
        ///  &quot;formattedTotalResults&quot;: &quot;0&quot;
        /// },
        /// &quot;spelling&quot;: {
        ///  &quot;correctedQuery&quot;: &quot;education&quot;
        /// }
        ///}.
        /// </summary>
        internal static string SpellingSuggestion {
            get {
                return ResourceManager.GetString("SpellingSuggestion", resourceCulture);
            }
        }
    }
}
